# Generated by Django 5.1.2 on 2024-12-13 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0007_comment_content_comment_downvotes_comment_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
    ]
